// Folder id → display label. Order here is the order on the site and in the README.
export const CATEGORIES = [
  ["general", "General"],
  ["arrows", "Arrows"],
  ["alerts-feedback", "Alerts & Feedback"],
  ["communication", "Communication"],
  ["users", "Users"],
  ["files", "Files"],
  ["editor", "Editor"],
  ["layout", "Layout"],
  ["images", "Images"],
  ["media-devices", "Media & Devices"],
  ["charts", "Charts"],
  ["development", "Development"],
  ["security", "Security"],
  ["finance-ecommerce", "Finance & E-commerce"],
  ["time", "Time"],
  ["maps-travel", "Maps & Travel"],
  ["education", "Education"],
  ["weather", "Weather"],
  ["shapes", "Shapes"],
];
