// Search words for every icon: what people type when they want it, beyond its file name.
// keywordsFor(cat, name) returns one lowercase string the site and the Figma plugin search through.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const FLAG_CODES = fs.existsSync(path.join(here, "flag-codes.json")) ? JSON.parse(fs.readFileSync(path.join(here, "flag-codes.json"), "utf8")) : {};

// Words that fit every icon in a category.
const CATEGORY = {
  "alerts-feedback": "alert feedback status notice",
  arrows: "arrow direction navigation",
  charts: "chart graph data analytics report",
  communication: "communication message talk contact",
  development: "development developer code programming software",
  editor: "editor text formatting writing",
  education: "education learning study school",
  files: "file document storage",
  "finance-ecommerce": "finance money payment shop commerce ecommerce",
  general: "general ui basic",
  images: "image photo picture media",
  layout: "layout ui structure",
  "maps-travel": "map travel location trip",
  "media-devices": "media device hardware",
  security: "security safety protection privacy",
  shapes: "shape geometry basic",
  time: "time date clock",
  users: "user people person account profile",
  weather: "weather forecast climate",
  cursors: "cursor mouse pointer",
  flags: "flag country nation",
};

// Words per icon name, shared by every category that uses the name.
const NAME = {
  // alerts & feedback
  "alert-circle": "warning error danger caution exclamation attention",
  "alert-square": "warning error danger caution exclamation attention",
  "alert-triangle": "warning error danger caution exclamation attention",
  "bell-ringing": "notification alarm ring reminder alert",
  bug: "error issue defect insect problem",
  "check-circle": "success done complete ok tick approved verified confirm",
  feedback: "review comment rating opinion suggestion",
  flag: "report mark bookmark milestone",
  headset: "support help customer service call center",
  "help-circle": "question support faq info unknown",
  "info-circle": "information about details help",
  "message-question": "faq ask question help chat support",
  "message-square": "chat comment conversation bubble",
  notification: "bell alert reminder badge",
  report: "flag issue complaint document",
  // arrows
  "arrow-down": "down south bottom descend",
  "arrow-left": "left back previous west",
  "arrow-right": "right next forward east",
  "arrow-up": "up north top ascend",
  "chevron-left": "back previous caret left",
  "chevron-right": "next forward caret right",
  "chevrons-down": "double down collapse expand",
  "chevrons-left": "double left rewind first",
  "chevrons-right": "double right fast forward last",
  "chevrons-up": "double up collapse",
  "expand-diagonal": "fullscreen enlarge maximize grow",
  "minimize-diagonal": "exit fullscreen shrink reduce collapse",
  refresh: "reload sync update repeat loop",
  "rotate-left": "undo counterclockwise turn",
  "rotate-right": "redo clockwise turn",
  // charts
  "area-chart": "graph analytics trend",
  "bar-chart": "graph analytics column stats",
  compare: "versus difference swap transfer",
  dashboard: "overview panel analytics widgets",
  "data-table": "table spreadsheet grid rows",
  gauge: "speed meter performance speedometer",
  histogram: "distribution bars graph",
  "line-chart": "graph trend analytics",
  metrics: "kpi analytics performance stats",
  "pie-chart": "donut graph share percentage",
  "scatter-plot": "dots graph correlation",
  statistics: "stats growth analytics",
  "trend-down": "decline loss decrease drop fall",
  "trend-up": "growth increase gain rise profit",
  // communication
  broadcast: "radio signal wifi antenna stream live podcast",
  chat: "message conversation talk bubble comment",
  contact: "address book phonebook person card",
  email: "mail envelope letter inbox message",
  inbox: "mail tray received messages",
  megaphone: "announcement marketing loudspeaker promote",
  message: "chat comment bubble conversation sms",
  "message-alert": "unread new message notification",
  messages: "chat conversation discussion group",
  outbox: "sent mail tray send",
  phone: "call telephone dial contact mobile",
  "video-call": "meeting zoom conference facetime camera",
  volume: "sound audio speaker loud",
  "volume-off": "mute silent sound off quiet",
  // development
  api: "integration endpoint connection plug",
  branch: "git fork version",
  cloud: "hosting storage sync upload server",
  code: "html brackets developer embed",
  commit: "git version save",
  database: "db storage data server sql",
  debug: "bug fix test inspect",
  deployment: "deploy launch rocket release ship",
  documentation: "docs manual guide book",
  merge: "git combine join",
  "pull-request": "git pr review merge",
  repository: "repo git project folder",
  server: "hosting backend rack host",
  terminal: "console command line shell cli prompt",
  // editor
  "align-center": "text center justify",
  "align-left": "text left justify",
  "align-right": "text right justify",
  bold: "strong text weight font",
  copy: "duplicate clone clipboard",
  cut: "scissors clipboard trim",
  edit: "pencil write modify pen compose",
  italic: "slant emphasis text font",
  "list-bulleted": "bullets unordered list items",
  "list-numbered": "ordered numbers list items",
  paste: "clipboard insert",
  redo: "forward repeat again",
  strikethrough: "strike delete text cross",
  underline: "text underscore font",
  undo: "back revert reverse",
  // education
  assignment: "homework task clipboard",
  blackboard: "chalkboard class teaching board",
  book: "read reading library novel",
  certificate: "award diploma achievement badge",
  diploma: "certificate graduation degree award",
  exam: "test quiz paper grade",
  "graduation-cap": "graduate degree university college school hat",
  lecture: "presentation class talk seminar",
  library: "books shelf archive",
  "online-course": "elearning video lesson webinar",
  quiz: "test question exam",
  school: "building education campus",
  student: "pupil learner person",
  teacher: "tutor instructor professor",
  tutorial: "guide lesson howto video",
  // files
  archive: "box storage store backup",
  attachment: "paperclip clip attach",
  document: "page paper doc text",
  "document-file": "word doc page",
  download: "save get arrow down",
  file: "page paper doc blank",
  folder: "directory storage collection",
  "folder-open": "directory browse open",
  "image-file": "photo picture jpg png",
  "pdf-file": "pdf document acrobat",
  save: "floppy disk store",
  "spreadsheet-file": "excel sheet xls csv table",
  upload: "send share arrow up",
  "video-camera": "video movie film record",
  "zip-file": "compressed archive rar",
  // finance & e-commerce
  bank: "finance building institution money",
  "credit-card": "payment card debit pay visa",
  discount: "coupon sale percent offer promo deal",
  dollar: "money usd currency price cash",
  euro: "money eur currency price",
  investment: "stocks growth portfolio money",
  invoice: "bill receipt payment document",
  "money-transfer": "send money payment transaction",
  pound: "money gbp sterling currency",
  receipt: "bill invoice purchase",
  sale: "tag price discount label",
  savings: "piggy bank money save",
  "shopping-cart": "cart basket buy shop checkout store",
  wallet: "money payment purse",
  yen: "money jpy currency",
  // general
  heart: "love like favorite favourite health",
  home: "house main start dashboard",
  lock: "secure private password locked",
  login: "sign in enter signin",
  logout: "sign out exit leave signout",
  menu: "hamburger navigation list bars",
  more: "dots ellipsis options overflow",
  search: "find magnifier magnifying glass lookup zoom",
  settings: "gear cog preferences options config",
  star: "favorite favourite rating bookmark",
  trash: "delete remove bin garbage rubbish",
  unlock: "open unlocked access",
  user: "person profile account avatar",
  // images
  background: "layer back image",
  brightness: "light sun exposure",
  camera: "photo picture snapshot",
  contrast: "tone half adjust",
  crop: "trim cut resize",
  filters: "adjust effects edit",
  foreground: "layer front image",
  gallery: "photos album pictures",
  "image-edit": "photo edit retouch",
  "image-frame": "photo picture frame",
  rotate: "turn spin",
  saturation: "color adjust vibrance",
  slideshow: "presentation slides carousel",
  snapshot: "screenshot capture photo",
  // layout
  columns: "grid split vertical",
  grid: "tiles layout dashboard squares",
  "horizontal-spacing": "gap distribute space",
  layers: "stack levels arrange",
  list: "rows items view",
  margin: "spacing outside space",
  maximize: "fullscreen expand",
  padding: "spacing inside space",
  rows: "horizontal stack lines",
  sidebar: "panel drawer navigation",
  "sliders-horizontal": "filter adjust settings controls",
  "split-view": "columns compare panes",
  // maps & travel
  airplane: "flight plane travel trip airport",
  bus: "transport transit public",
  car: "vehicle drive auto transport",
  compass: "navigation direction explore",
  direction: "signpost route way navigation",
  gps: "location locate target crosshair",
  hotel: "bed stay lodging accommodation",
  landmark: "monument building museum bank",
  map: "location area navigation",
  "map-pin": "location place marker pin address",
  passport: "travel id identity document",
  route: "path way navigation directions",
  suitcase: "luggage bag travel briefcase work",
  "suitcase-filled": "luggage bag travel briefcase work",
  ticket: "pass admission event coupon",
  train: "rail railway transport subway metro",
  // media & devices
  gamepad: "controller game gaming joystick play",
  headphones: "music audio listen headset",
  laptop: "computer notebook macbook",
  microphone: "mic record voice audio podcast",
  monitor: "screen display desktop computer",
  "music-note": "music song audio melody",
  pause: "stop hold break",
  play: "start video music run",
  record: "rec dot capture",
  smartphone: "phone mobile iphone cell",
  stop: "end halt square",
  tablet: "ipad device",
  // security
  antivirus: "virus protection malware scan",
  encryption: "encrypt secure crypto lock",
  fingerprint: "biometric touch id identity",
  firewall: "network protection wall",
  key: "password access unlock",
  password: "pin code secret login",
  privacy: "private eye hide visibility",
  safe: "vault deposit secure",
  shield: "protection secure guard",
  "user-shield": "protected account guard",
  vpn: "network secure tunnel",
  // shapes
  check: "tick done yes ok correct",
  circle: "round dot ring",
  diamond: "rhombus gem",
  hexagon: "polygon six",
  minus: "subtract remove dash less",
  oval: "ellipse round",
  pentagon: "polygon five",
  plus: "add new create more",
  rectangle: "box square",
  square: "box block",
  triangle: "delta play",
  x: "close cancel cross remove delete",
  // time
  "alarm-clock": "alarm wake reminder",
  calendar: "date schedule month event",
  clock: "time hour watch",
  countdown: "timer deadline",
  date: "calendar day",
  event: "calendar meeting appointment",
  history: "recent past time back",
  hourglass: "wait loading time",
  planner: "schedule agenda calendar",
  reminder: "alarm bell notify",
  schedule: "calendar plan agenda",
  stopwatch: "timer speed lap",
  timeline: "history roadmap progress",
  timer: "countdown clock",
  "world-time": "timezone global clock",
  // users
  admin: "administrator manager superuser",
  moderator: "mod admin manager",
  "user-activity": "status online pulse",
  "user-blocked": "ban block forbidden",
  "user-circle": "avatar profile account",
  "user-follow": "add follow connect",
  "user-list": "members directory contacts",
  "user-minus": "remove delete member",
  "user-plus": "add invite new member",
  "user-role": "permissions role access",
  "user-settings": "account preferences profile",
  "user-statistics": "analytics insights",
  "user-unfollow": "remove unfollow disconnect",
  "user-verified": "verified badge check approved",
  users: "team group people members community",
  // weather
  fog: "mist haze cloudy",
  hurricane: "storm cyclone typhoon",
  moon: "night dark mode sleep",
  rain: "rainy drops shower wet",
  snowflake: "snow winter cold freeze",
  "snowflake-filled": "snow winter cold freeze",
  sun: "sunny day light mode bright",
  sunrise: "morning dawn",
  sunset: "evening dusk",
  thermometer: "temperature heat degree",
  thunderstorm: "lightning storm thunder bolt",
  tornado: "twister storm wind",
  umbrella: "rain protection insurance",
  wind: "breeze air windy",
  // cursors
  arrow: "default select normal",
  cell: "plus select spreadsheet",
  cross: "crosshair precise select",
  "figma-cursor": "figma collaborator multiplayer arrow",
  "figma-hand": "figma hand pan grab",
  grab: "hand pan drag",
  grabbing: "hand drag dragging closed",
  help: "question what",
  loading: "wait busy spinner beachball progress",
  move: "drag reposition arrows",
  "not-allowed": "forbidden blocked no disabled",
  pointer: "hand click link finger",
  poof: "remove disappear delete",
  screenshot: "capture camera",
  "screenshot-select": "capture area region",
  text: "type ibeam caret input",
  "text-vertical": "type ibeam vertical",
  "zoom-in": "magnify enlarge plus",
  "zoom-out": "magnify shrink minus",
  alias: "shortcut link",
};

// Names that mean something different in one category.
const SPECIFIC = {
  "security/camera": "cctv surveillance security camera monitor",
  "media-devices/camera": "photo picture capture",
  "images/camera": "photo picture capture",
  "weather/star": "night sky",
  "shapes/heart": "love",
  "shapes/arrow-right": "next",
  "development/bug": "debug",
  "development/cloud": "devops",
};

// Other names people use for a country or region.
const FLAG_ALIASES = {
  US: "usa america united states american", GB: "uk britain great britain england british", AE: "uae emirates dubai",
  KR: "korea", KP: "korea dprk", CN: "china prc chinese", TW: "taiwan", RU: "russia", NL: "holland dutch",
  DE: "germany deutschland german", FR: "france french", ES: "spain espana spanish", IT: "italy italian", JP: "japan nippon japanese",
  ID: "indonesia indonesian", IN: "india bharat indian", BR: "brazil brasil", MX: "mexico mexican", CH: "switzerland swiss",
  EU: "europe european union", CZ: "czechia czech republic", CI: "cote divoire", CD: "democratic republic congo drc", MM: "burma",
  VA: "vatican holy see", SZ: "swaziland eswatini", MK: "macedonia", TR: "turkey turkiye", PH: "philippines filipino",
  SA: "saudi", NZ: "new zealand kiwi aotearoa", AU: "australia aussie", CA: "canada canadian", ZA: "south africa",
};

const words = (s) => s.split(/[\s-]+/).filter(Boolean);
export function keywordsFor(cat, name) {
  const out = new Set();
  for (const w of words(name)) out.add(w);
  for (const src of [NAME[name], SPECIFIC[`${cat}/${name}`], CATEGORY[cat]]) if (src) for (const w of words(src)) out.add(w);
  if (cat === "flags") {
    const code = FLAG_CODES[name];
    if (code) { out.add(code.toLowerCase()); if (FLAG_ALIASES[code]) for (const w of words(FLAG_ALIASES[code])) out.add(w); }
    out.delete("flag"); out.add("flag");
  }
  if (cat === "cursors" && name.startsWith("resize-")) for (const w of words("scale stretch size drag")) out.add(w);
  if (cat === "cursors" && name.startsWith("rotate-")) for (const w of words("turn spin corner")) out.add(w);
  return [...out].join(" ");
}
